# The Docker image that will be used to build your app
image: python:latest
# Functions that should be executed before the build script is run
before_script:
  - pip install -e .[doc]
pages:
  script:
    - sphinx-apidoc -M -e -f --implicit-namespaces -o docs/source/ src/geosolver
    - python docs/reformat.py
    - sphinx-build -b html ./docs public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
